services:
  the_klontongs:
    image: brik_klt:latest
    env_file:
      - .env
    ports:
      - '3000:3000'

  databaseServices:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: BRIK_MARKETPLACE_DB  
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"